package llm

import (
	"github.com/prometheus/client_golang/prometheus"
)

type Metrics struct {
	PromptTokensTotal       *prometheus.CounterVec
	CachedPromptTokensTotal *prometheus.CounterVec
	CompletionTokensTotal   *prometheus.CounterVec
	CostUSDTotal            *prometheus.CounterVec
	LLMDurationSeconds      *prometheus.HistogramVec
}

func NewMetrics(reg prometheus.Registerer, namespace, subsystem string) *Metrics {
	if reg == nil {
		reg = prometheus.DefaultRegisterer
	}

	m := &Metrics{
		PromptTokensTotal: registerOrGet(reg, prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: namespace,
				Subsystem: subsystem,
				Name:      "llm_prompt_tokens_total",
				Help:      "Total number of input prompt tokens processed by LLMs.",
			},
			[]string{"model", "action", "tenant"},
		)),
		CachedPromptTokensTotal: registerOrGet(reg, prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: namespace,
				Subsystem: subsystem,
				Name:      "llm_cached_prompt_tokens_total",
				Help:      "Total number of cached input tokens (prompt cache hits) processed by LLMs.",
			},
			[]string{"model", "action", "tenant"},
		)),
		CompletionTokensTotal: registerOrGet(reg, prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: namespace,
				Subsystem: subsystem,
				Name:      "llm_completion_tokens_total",
				Help:      "Total number of completion tokens generated by LLMs.",
			},
			[]string{"model", "action", "tenant"},
		)),
		CostUSDTotal: registerOrGet(reg, prometheus.NewCounterVec(
			prometheus.CounterOpts{
				Namespace: namespace,
				Subsystem: subsystem,
				Name:      "llm_cost_usd_total",
				Help:      "Total estimated cost in USD for LLM usage.",
			},
			[]string{"model", "action", "tenant"},
		)),
		LLMDurationSeconds: registerOrGet(reg, prometheus.NewHistogramVec(
			prometheus.HistogramOpts{
				Namespace: namespace,
				Subsystem: subsystem,
				Name:      "llm_duration_seconds",
				Help:      "Duration of LLM calls in seconds.",
				Buckets:   []float64{0.1, 0.5, 1, 2, 5, 10, 30, 60},
			},
			[]string{"model", "action", "tenant"},
		)),
	}

	return m
}

func registerOrGet[T prometheus.Collector](reg prometheus.Registerer, collector T) T {
	if err := reg.Register(collector); err != nil {
		if are, ok := err.(prometheus.AlreadyRegisteredError); ok {
			if existing, ok := are.ExistingCollector.(T); ok {
				return existing
			}
		}
	}
	return collector
}
